### ISSUE TITLE
[InstantCommands] `issubclass() arg 1 must be a class` error on `[p]instacmd create`

### ISSUE THREAD

**Issue by japandotorg** [retke/Laggrons-Dumb-Cogs#210]
### Red's version

3.5.2

### The cog you're using.

InstantCommands

### The cog's version

2.0.0

### The command you're using

instacmd create

### What did you expect to happen?

To get my instacmd snippet added.

### What actually happened?

error out with this traceback -
```py
Traceback (most recent call last):
  File "{HOME}/MELON/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/.local/share/Red-DiscordBot/data/MELON/cogs/CogManager/cogs/instantcmd/instantcmd.py", line 277, in create
    snippet_type = find_matching_type(function)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/.local/share/Red-DiscordBot/data/MELON/cogs/CogManager/cogs/instantcmd/code_runner.py", line 72, in find_matching_type
    if isinstance(code, source) or issubclass(code, source):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "{HOME}/MELON/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "{HOME}/melon-dpy2/redbot/core/commands/commands.py", line 783, in invoke
    await super().invoke(ctx)
  File "{HOME}/MELON/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1650, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "{HOME}/MELON/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/MELON/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: issubclass() arg 1 must be a class
```

### How can we reproduce this error?

1. Load instacmd
2. use this command
`[p]instacmd create`
```py
from redbot.core import commands
from instantcmd.utils import dev_env_value

@dev_env_value()
def reply(ctx: commands.Context):
    if hasattr(ctx.message, "reference") and ctx.message.reference != None:
        msg = ctx.message.reference.resolved
        if isinstance(msg, discord.Message):
             return msg

return reply
```

**Comment by laggron42** [comment]
Thanks for the report and sorry for the delay, it's fixed now

**Comment by qenu** [comment]
Seems like the same issue as #210, and `issubclass` was re-added in b9c90d7abd12ce4689500b479c0c865e3497f82b

**Red's version**
3.5.6

**The cog you're using.**
InstantCommands

**The cog's version**
2.0.2

**Error log**
```py
Exception in command 'instantcmd create'
Traceback (most recent call last):
  File "/home/qenu/botenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/qenu/bot_data/enul/cogs/CogManager/cogs/instantcmd/instantcmd.py", line 276, in create
    snippet_type = find_matching_type(function)
  File "/home/qenu/bot_data/enul/cogs/CogManager/cogs/instantcmd/code_runner.py", line 70, in find_matching_type
    if issubclass(code, discord.ui.View):
TypeError: issubclass() arg 1 must be a class

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/qenu/botenv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/qenu/botenv/lib/python3.9/site-packages/redbot/core/commands/commands.py", line 825, in invoke
    await super().invoke(ctx)
  File "/home/qenu/botenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1650, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/qenu/botenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/qenu/botenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: issubclass() arg 1 must be a class
```

**Reproduce**
`instacmd create` 
```py
from redbot.cogs.downloader.converters import InstalledCog

@commands.command()
@commands.max_concurrency(1)
@commands.is_owner()
async def cu(ctx, *cogs: InstalledCog):
    """Update cogs without questioning about reload"""
    await ctx.invoke(bot.get_command("cog update"), True, *cogs)

return cu
```
