### ISSUE TITLE
Warnsystem Issues

### ISSUE THREAD

**Issue by EternalllZM** [retke/Laggrons-Dumb-Cogs#211]
### Red's version

3.5.2

### The cog you're using.

WarnSystem

### The cog's version

1.5.0

### What did you expect to happen?

The following is broken on the dpy2 release (and partially on the 3.4.X release)

- Cannot view warnings of banned users
- Timed mutes/unbans do not work
- Masswarn does not work

### What actually happened?

Cannot edit or delete warnings, cannot view banned users warnings

Buttons do not work (reaction for 3.4.X deletion does not work)

### Banned user error:
```
Traceback (most recent call last):
  File "/home/red/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/red/.local/share/Red-DiscordBot/data/modet/cogs/CogManager/cogs/warnsystem/warnsystem.py", line 759, in warnings
    embed.set_author(name=f"{user} | {user.id}", icon_url=user.avatar.url)
                                                          ^^^^^^^^^^^
AttributeError: 'UnavailableMember' object has no attribute 'avatar'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/red/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/red/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/red/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'UnavailableMember' object has no attribute 'avatar'
```
### Timed unmutes/bans issue
```
[2023-07-22 22:36:30] [CRITICAL] red.laggron.warnsystem: The loop for unmutes and unbans encountered a third error. To prevent more damages, the loop will be cancelled. Timed mutes and bans no longer works for now. Reload the cog to start the loop back. If the problem persists, report the error and update the cog.
Traceback (most recent call last):
  File "/home/red/.local/share/Red-DiscordBot/data/red/cogs/CogManager/cogs/warnsystem/api.py", line 1427, in _loop_task
    await self._check_endwarn()
  File "/home/red/.local/share/Red-DiscordBot/data/red/cogs/CogManager/cogs/warnsystem/api.py", line 1373, in _check_endwarn
    if (taken_on + duration) < now:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
```

### How can we reproduce this error?

1. View warnings of a banned user
2. Attempt to edit warnings of a user
3. Attempt to delete warnings of a user
4. Create a timed mute and it will not remove itself
5. Attempt to run masswarn at all

### Anything else?

I know dpy2 version is not complete yet, but these core functions should be hotfixed before a major rewrite or any further feature releases. The cog just simply isn't that functional without the ability to reference and edit the modlog.

**Comment by EternalllZM** [comment]
Edited original post to include the error of timed unmutes/unbans not working. Loop gets stopped due to error.

**Comment by EternalllZM** [comment]
Added extra info about masswarn being completely non-functional.
