### ISSUE TITLE
JSONDecodeError when starting the bot

### ISSUE THREAD

**Issue by thisisjvgrace** [retke/Laggrons-Dumb-Cogs#37]
### Source of the problem

- [ ] Say
- [ ] RoleInvite
- [x] Other

### Description

I was checking my journalctl logs just now and seeing this traceback related to your repo, so I'm just reporting this here. This appears on console when starting the bot fresh.:
I'm on V3 RC2. 
```py
Jan 07 21:54:33 zeno redbot[31243]: [07/01/2019 21:54] ERROR installable _process_info_file 149: Invalid JSON information file at path: /home/flux/bot/cogs/RepoManager/repos/laggron/signal_handle
Jan 07 21:54:33 zeno redbot[31243]: Traceback (most recent call last):
Jan 07 21:54:33 zeno redbot[31243]:   File "/home/flux/.local/lib/python3.6/site-packages/redbot/cogs/downloader/installable.py", line 146, in _process_info_file
Jan 07 21:54:33 zeno redbot[31243]:     info = json.load(f)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/__init__.py", line 299, in load
Jan 07 21:54:33 zeno redbot[31243]:     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
Jan 07 21:54:33 zeno redbot[31243]:     return _default_decoder.decode(s)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
Jan 07 21:54:33 zeno redbot[31243]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
Jan 07 21:54:33 zeno redbot[31243]:     obj, end = self.scan_once(s, idx)
Jan 07 21:54:33 zeno redbot[31243]: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 10 column 1 (char 405)
Jan 07 21:54:33 zeno redbot[31243]: [07/01/2019 21:54] ERROR installable _process_info_file 149: Invalid JSON information file at path: /home/flux/bot/cogs/RepoManager/repos/laggron/signal_handle
Jan 07 21:54:33 zeno redbot[31243]: Traceback (most recent call last):
Jan 07 21:54:33 zeno redbot[31243]:   File "/home/flux/.local/lib/python3.6/site-packages/redbot/cogs/downloader/installable.py", line 146, in _process_info_file
Jan 07 21:54:33 zeno redbot[31243]:     info = json.load(f)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/__init__.py", line 299, in load
Jan 07 21:54:33 zeno redbot[31243]:     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
Jan 07 21:54:33 zeno redbot[31243]:     return _default_decoder.decode(s)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
Jan 07 21:54:33 zeno redbot[31243]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
Jan 07 21:54:33 zeno redbot[31243]:     obj, end = self.scan_once(s, idx)
Jan 07 21:54:33 zeno redbot[31243]: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 10 column 1 (char 405)
Jan 07 21:54:33 zeno redbot[31243]: [07/01/2019 21:54] ERROR installable _process_info_file 149: Invalid JSON information file at path: /home/flux/bot/cogs/RepoManager/repos/laggron/signal_handle
Jan 07 21:54:33 zeno redbot[31243]: Traceback (most recent call last):
Jan 07 21:54:33 zeno redbot[31243]:   File "/home/flux/.local/lib/python3.6/site-packages/redbot/cogs/downloader/installable.py", line 146, in _process_info_file
Jan 07 21:54:33 zeno redbot[31243]:     info = json.load(f)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/__init__.py", line 299, in load
Jan 07 21:54:33 zeno redbot[31243]:     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
Jan 07 21:54:33 zeno redbot[31243]:     return _default_decoder.decode(s)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
Jan 07 21:54:33 zeno redbot[31243]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
Jan 07 21:54:33 zeno redbot[31243]:     obj, end = self.scan_once(s, idx)
Jan 07 21:54:33 zeno redbot[31243]: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 10 column 1 (char 405)
Jan 07 21:54:33 zeno redbot[31243]: [07/01/2019 21:54] ERROR installable _process_info_file 149: Invalid JSON information file at path: /home/flux/bot/cogs/RepoManager/repos/laggron/signal_handle
Jan 07 21:54:33 zeno redbot[31243]: Traceback (most recent call last):
Jan 07 21:54:33 zeno redbot[31243]:   File "/home/flux/.local/lib/python3.6/site-packages/redbot/cogs/downloader/installable.py", line 146, in _process_info_file
Jan 07 21:54:33 zeno redbot[31243]:     info = json.load(f)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/__init__.py", line 299, in load
Jan 07 21:54:33 zeno redbot[31243]:     parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
Jan 07 21:54:33 zeno redbot[31243]:     return _default_decoder.decode(s)
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
Jan 07 21:54:33 zeno redbot[31243]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Jan 07 21:54:33 zeno redbot[31243]:   File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
Jan 07 21:54:33 zeno redbot[31243]:     obj, end = self.scan_once(s, idx)
Jan 07 21:54:33 zeno redbot[31243]: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 10 column 1 (char 405)
```

### Steps to reproduce

1.
2.
3.
...

### Redbot context

Discord.py's version:

Red-DiscordBot last commit:

Your cog's version:

**Comment by retke** [comment]
That cog was removed since it's included into the core Red now.
