### ISSUE TITLE
[BUG V3] roleInvite is unable to add role

### ISSUE THREAD

**Issue by Alpha272** [retke/Laggrons-Dumb-Cogs#49]
### Source of the problem

- [ ] InstantCommands
- [x] RoleInvite
- [ ] Say
- [ ] WarnSystem
- [ ] Other

### Description

The command [p]inviteset add <invite> <role> fails.
(Error in command 'inviteset add'. Check your console or logs for details.)

Additionally the bot is not able to show the roles with "[p]inviteset list", if there is at least one role in the settings.json (I grabbed a json from a former version, where everything was working), and the bot is unable to add the roles to the users, if there is at least one role in settings.json.

### Steps to reproduce

1. Give the bot all the permission necessary to add users to roles
2. Create a new role below the highest role the bot has
3. Create an Invite link
4. Execute the command "[p]inviteset add \<invite> \<role>"

### Expected behaviour

The bot adds the invite and the role into the settings.json

#### For "[p]inviteset add":

Exception in command 'inviteset add'
Traceback (most recent call last):
  File "c:\users\admin\redbot\lib\site-packages\discord\ext\commands\core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Red-DiscordBot\bot1\cogs\CogManager\cogs\roleinvite\roleinvite.py", line 231, in add
    await self.api.add_invite(ctx.guild, invite.url, [role.id])
  File "C:\Users\admin\AppData\Local\Red-DiscordBot\bot1\cogs\CogManager\cogs\roleinvite\api.py", line 152, in add_invite
    invite_object = await self.bot.get_invite(invite)
AttributeError: 'Red' object has no attribute 'get_invite'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\admin\redbot\lib\site-packages\discord\ext\commands\bot.py", line 860, in invoke
    await ctx.command.invoke(ctx)
  File "c:\users\admin\redbot\lib\site-packages\redbot\core\commands\commands.py", line 566, in invoke
    await super().invoke(ctx)
  File "c:\users\admin\redbot\lib\site-packages\discord\ext\commands\core.py", line 1127, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "c:\users\admin\redbot\lib\site-packages\discord\ext\commands\core.py", line 698, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "c:\users\admin\redbot\lib\site-packages\discord\ext\commands\core.py", line 72, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Red' object has no attribute 'get_invite'

#### For "[p]inviteset list":

Exception in command 'inviteset list'
Traceback (most recent call last):
  File "c:\users\admin\redbot\lib\site-packages\discord\ext\commands\core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Red-DiscordBot\bot1\cogs\CogManager\cogs\roleinvite\roleinvite.py", line 335, in list
    await self.bot.get_invite(i)
AttributeError: 'Red' object has no attribute 'get_invite'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\admin\redbot\lib\site-packages\discord\ext\commands\bot.py", line 860, in invoke
    await ctx.command.invoke(ctx)
  File "c:\users\admin\redbot\lib\site-packages\redbot\core\commands\commands.py", line 566, in invoke
    await super().invoke(ctx)
  File "c:\users\admin\redbot\lib\site-packages\discord\ext\commands\core.py", line 1127, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "c:\users\admin\redbot\lib\site-packages\discord\ext\commands\core.py", line 698, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "c:\users\admin\redbot\lib\site-packages\discord\ext\commands\core.py", line 72, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Red' object has no attribute 'get_invite'

### Redbot context

Discord.py's version: 1.0.1

Red-DiscordBot last commit: 3.1.1

Your cog's version: 2.0.0

### Additional context

I use a windows server 2019 for the bot and everything was working fine, until I updated the redbot to the lastest version (I needed to reinstall the whole bot, because the updater throw an error and the bot stopped working after that). After I updated everything and reinstalled the roleinvite cog, the cog just refused to work at all. The only command that works is the enable command.

This bug is on V3.

**Comment by retke** [comment]
This is due to discord.py's breaking changes introduced in the 3.1 version of Red, some functions needs to be renamed and I'm currently working on this.
The patch will most likely be pushed today or tomorrow.

**Comment by retke** [comment]
Resolved in #50 👍
