### ISSUE TITLE
Error in command 'wsunmute'. Check your console or logs for details

### ISSUE THREAD

**Issue by Skyridr** [retke/Laggrons-Dumb-Cogs#84]
Whenever I unmute someone with wsunmute, it seems to be not working.

```
Traceback (most recent call last):
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/satan/satan/cogs/CogManager/cogs/esf-warnsystem/warnsystem.py", line 1240, in wsunmute
    case = await self.cache.get_temp_action(guild, member)
  File "/home/satan/satan/cogs/CogManager/cogs/esf-warnsystem/cache.py", line 78, in get_temp_action
    return guild_temp_actions.get(member.id)
AttributeError: 'list' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'list' object has no attribute 'get'
```

**Comment by laggron42** [comment]
This issue is related to a badly converted config and has been fixed in DM. Check [the doc for data conversion](https://laggron.red/warnsystem.html#temporary-warnings-are-stored-as-a-dictionnary-instead-of-a-list) if you have this issue.
