### ISSUE TITLE
Error in command 'warn 2'. Check your console or logs for details.

### ISSUE THREAD

**Issue by Skyridr** [retke/Laggrons-Dumb-Cogs#86]
Apparently mute (warn 2) is also broken I'm afraid:

```
Traceback (most recent call last):
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/satan/satan/cogs/CogManager/cogs/esf-warnsystem/warnsystem.py", line 568, in warn_2
    await self.call_warn(ctx, 2, member, reason, time)
  File "/home/satan/satan/cogs/CogManager/cogs/esf-warnsystem/warnsystem.py", line 274, in call_warn
    fail = await self.api.warn(ctx.guild, [member], ctx.author, level, reason, time)
  File "/home/satan/satan/cogs/CogManager/cogs/esf-warnsystem/api.py", line 1081, in warn
    fails = [await warn_member(x, audit_reason) for x in members if x]
  File "/home/satan/satan/cogs/CogManager/cogs/esf-warnsystem/api.py", line 1081, in <listcomp>
    fails = [await warn_member(x, audit_reason) for x in members if x]
  File "/home/satan/satan/cogs/CogManager/cogs/esf-warnsystem/api.py", line 1005, in warn_member
    await self._start_timer(guild, member, data)
  File "/home/satan/satan/cogs/CogManager/cogs/esf-warnsystem/api.py", line 205, in _start_timer
    await self.cache.add_temp_action(guild, member, case)
  File "/home/satan/satan/cogs/CogManager/cogs/esf-warnsystem/cache.py", line 81, in add_temp_action
    await self.data.guild(guild).temporary_warns.set_raw(member.id, value=data)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/redbot/core/config.py", line 589, in set_raw
    await self.driver.set(identifier_data, value=value)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/redbot/core/drivers/json.py", line 156, in set
    partial[full_identifiers[-1]] = value_copy
TypeError: list indices must be integers or slices, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
```
```
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 799, in invoke
    await super().invoke(ctx)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/satan/.virtualenvs/satan/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: list indices must be integers or slices, not str
```

Seems to be similar to the error of unmute: https://github.com/retke/Laggrons-Dumb-Cogs/issues/84

**Comment by laggron42** [comment]
This issue is related to a badly converted config and has been fixed in DM. Check [the doc for data conversion](https://laggron.red/warnsystem.html#temporary-warnings-are-stored-as-a-dictionnary-instead-of-a-list) if you have this issue.
